SELECT s.SUPPLIER_NAME, p.PRICE
FROM SUPPLIER s
JOIN SUPPLY su ON s.SUPPLIER_CODE = su.CODE_SUPPLIER
JOIN PART p ON su.CODE_PIECE = p.CODE_PART
JOIN CAR c ON su.CODE_CAR = c.CODE_CAR
WHERE s.CITY = 'VITORIA'
AND p.NAME_PART = 'MOTOR'
AND c.NAME_CAR = 'KOMBI';